# https://pre-commit.com/
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/python/black
    # rev: stable
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  # conflicts with black
  # - repo: https://github.com/pre-commit/mirrors-autopep8
  #   rev: v1.6.0
  #   hooks:
  #     - id: autopep8
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args:
          - "--py3-only"
          - "--py37-plus"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    - id: mypy
      additional_dependencies: [types-all]
      # exclude: ^testing/resources/
  - repo: meta
    hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes