# https://pre-commit.com/
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/python/black
    # rev: stable
    rev: 21.5b2
    hooks:
      - id: black
 # - repo: local
 #   hooks:
 #     - id: pylint
 #       name: pylint
 #       entry: pylint
 #       language: system
 #       types: [python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v0.761  # Must match ci/requirements/*.yml
  #  hooks:
  #    - id: mypy
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.3
    hooks:
      - id: pyupgrade
        args:
          - "--py3-only"
          - "--py37-plus"
