from __future__ import annotations

import os
import re
import subprocess
import sys
from os.path import isdir, split
from pathlib import Path
from typing import IO, TYPE_CHECKING, Any, TextIO

import click

from ..core import find_application, get_app_entrypoint, get_route_prefixes, get_static_folders_for_app
from ..templating import get_template, undefined_error
from ..utils import StaticFolder, has_package, topath, which
from .cli import config
from .utils import (
    CHECKTYPE,
    CONVERTER,
    asgi_option,
    check_app_dir,
    config_options,
    find_toplevel,
    fix_params,
    footprint_config,
    get_known,
    has_error_page,
    make_args,
    template_option,
    to_check_func,
    to_output,
    url_match,
)

if TYPE_CHECKING:
    import threading
    from collections.abc import Callable
    from threading import Thread

    from jinja2 import Template


def ensure_package(exe: str) -> None:
    if not has_package(exe):
        click.secho(
            f"{exe} is not installed. Please install it with `pip install {exe}`",
            fg="red",
            bold=True,
            err=True,
        )
        raise click.Abort


def run_app(
    application_dir: Path,
    bind: str,
    entrypoint: str,
    *,
    asgi: bool = False,
    args: tuple[str, ...] = (),
) -> subprocess.Popen[bytes]:

    if asgi:
        if not bind.startswith("unix:"):
            msg = f"ASGI apps must use a unix socket. Got {bind}"
            raise ValueError(msg)
        bind = bind[len("unix:") :]
        exe = "uvicorn"
        cmd = [
            sys.executable,
            "-m",
            exe,
            "--proxy-headers",
            f"--uds={bind}",
            *args,
            entrypoint,
        ]

    else:
        exe = "gunicorn"
        cmd = [
            sys.executable,
            "-m",
            exe,
            "--access-logfile=-",
            "--error-logfile=-",
            "--bind",
            bind,
            *args,
            entrypoint,
        ]

    ensure_package(exe)
    click.secho(
        f"starting {exe} in {topath(application_dir)}",
        fg="green",
        bold=True,
    )

    click.secho(" ".join(cmd), fg="yellow")
    return subprocess.Popen(cmd, cwd=application_dir, env=os.environ)


def patch_nginx_conf(oldfile: Path, newfile: Path) -> Path:  # noqa: C901
    """Ensure we don't overwrite any existing nginx configuration that has been patched by certbot or other tools."""
    newlines: list[str] = []
    active: bool = False
    with newfile.open("rt", encoding="utf-8") as fp:
        for line in fp:
            if line.lstrip().startswith("# >>> generated by footprint"):
                active = True
            elif line.lstrip().startswith("# <<< generated by footprint"):
                break
            elif active:
                newlines.append(line)
    if not newlines:
        return newfile
    nnewfile = newfile.parent / f"{newfile.stem}-patched{newfile.suffix}"
    certbot = "# managed by Certbot" in oldfile.read_text(encoding="utf-8")
    with nnewfile.open("wt", encoding="utf-8") as fp:
        patched = False
        active = False

        with oldfile.open("rt", encoding="utf-8") as olfp:
            for line in olfp:
                if line.lstrip().startswith("# >>> generated by footprint"):
                    active = True
                    fp.write(line)
                    for newline in newlines:
                        # skip any listen lines if certbot has already added them
                        if certbot and newline.lstrip().startswith("listen"):
                            continue
                        fp.write(newline)
                    patched = True
                elif line.lstrip().startswith("# <<< generated by footprint"):
                    active = False
                    fp.write(line)
                elif not active:
                    fp.write(line)
    if not patched:
        nnewfile.unlink(missing_ok=True)
        return newfile
    click.secho(
        f"patched {oldfile.name} to {nnewfile.name}",
        fg="yellow",
        bold=True,
        err=True,
    )
    return nnewfile


def nginx_install(nginxconf: str, *, check_only: bool = False) -> str | None:  # noqa: C901, PLR0915, PLR0912
    import filecmp

    from ..config import get_config

    nginxfile = Path(nginxconf)

    config = get_config()

    conf = nginxfile.name
    # Ubuntu, RHEL8
    for td in config.nginx_dirs:
        targetd = Path(td)
        if targetd.is_dir():
            break
    else:
        msg = "can't find nginx configuration directory."
        raise RuntimeError(msg)
    sudo = which("sudo")
    systemctl = which("systemctl")

    def sudocmd(*args: Any, check: bool = True) -> subprocess.CompletedProcess[bytes]:  # noqa: ANN401
        return subprocess.run([sudo] + [str(a) for a in args], check=check)

    def runcmd(*args: Any, check: bool = True) -> subprocess.CompletedProcess[bytes]:  # noqa: ANN401
        return subprocess.run([str(a) for a in args], check=check)

    def systemctlcmd(*args: Any, check: bool = True) -> int:  # noqa: ANN401
        return subprocess.run(
            [sudo, systemctl] + [str(a) for a in args],
            check=check,
        ).returncode

    conffile = targetd / conf

    exists = conffile.is_file()
    issame = exists and filecmp.cmp(conffile, nginxfile)
    if check_only:
        if exists:
            if issame:
                click.secho(
                    f"nginx file {conf} {'unchanged' if issame else 'changed'}",
                    fg="green" if issame else "yellow",
                )
        else:
            click.secho(f"installed nginx file {conf} does not exist", fg="yellow")
        return None

    if not issame:
        bak = None
        if exists:
            bak = nginxfile.parent / f"{conffile.name}.bak"
            runcmd("cp", conffile, bak)
            # file might have been patched by certbot or other tools so we need to patch it
            nnginxfile = patch_nginx_conf(conffile, nginxfile)
            if filecmp.cmp(conffile, nnginxfile):
                click.secho(f"nginx file {conf} unchanged", fg="green")
                if bak is not None:
                    bak.unlink(missing_ok=True)
                if nnginxfile != nginxfile:
                    nnginxfile.unlink(missing_ok=True)
                return conf
            click.secho(f"warning: overwriting old {conf}", fg="yellow")
            sudocmd("cp", nnginxfile, conffile)
            if nnginxfile != nginxfile:
                nnginxfile.unlink(missing_ok=True)
        else:
            sudocmd("cp", nginxfile, conffile)

        if sudocmd("nginx", "-t", check=False).returncode != 0:
            sudocmd("rm", conffile)
            if bak is not None:
                sudocmd("mv", bak, conffile)
            click.secho("nginx configuration faulty", fg="red", err=True)
            return None if bak is None else conf
        if bak is not None:
            bak.unlink(missing_ok=True)

        systemctlcmd("restart", "nginx")
    else:
        click.secho(f"nginx file {conf} unchanged", fg="green")
    return conf


def nginx_uninstall(nginxconf: str) -> None:
    from ..config import get_config

    config = get_config()
    nginxfile = Path(nginxconf)
    conf = nginxfile.name
    if "." not in conf:
        conf += ".conf"
    sudo = which("sudo")
    systemctl = which("systemctl")

    def sudocmd(*args: str, check: bool = True) -> subprocess.CompletedProcess[bytes]:
        return subprocess.run([sudo, *args], check=check)

    def systemctlcmd(*args: str, check: bool = True) -> int:
        return subprocess.run([sudo, systemctl, *args], check=check).returncode

    for d in config.nginx_dirs:
        fname = Path(d) / conf
        if fname.is_file():
            sudocmd("rm", str(fname))
            systemctlcmd("restart", "nginx.service")
            return

    click.secho(f"no nginx file {nginxfile}", fg="yellow", err=True)


NGINX_ARGS = {
    "server_name": "name of website",
    "application_dir": "locations of repo",
    "app": "entrypoint to app",
    "appname": "application name [default: directory name]",
    "root": "static files root directory",
    "root_prefix": "location prefix to use (only used if root is defined)",
    "prefix": "url prefix for application [default: /]",
    "expires": "expires header for static files [default: off] e.g. 30d",
    "listen": "listen on port [default: 80]",
    "host": "proxy to a port [default: use unix socket]",
    "port": "TCP/IP port to use",
    "root_location_match": "regex for matching static directory files",
    "access_log": "'on' or 'off'. log static asset requests [default:off]",
    "extra": "extra (legal) nginx commands for proxy",
    "log_format": "specify the log_format",
    "authentication": "authentication file",
    "exclude_urls": "list of urls to immediately return 404 for (one per line)",
}

NGINX_HELP = f"""
Generate a nginx conf file for website.

Use footprint config nginx website ... etc.
with the following arguments:

\b
{make_args(NGINX_ARGS)}
\b
example:
\b
footprint config nginx mcms.plantenergy.edu.au access-log=on
\b
"""


def appname_func(params: dict[str, Any]) -> str:
    app = str(params["application_dir"])
    return str(split(app)[-1])


def fix_path(s: str) -> str:
    return s.removeprefix("/")


def nginx(  # noqa: C901, PLR0915, PLR0912
    application_dir: Path,
    server_name: str,
    args: list[str] | None = None,
    *,
    template_name: str | None = None,
    help_args: dict[str, str] | None = None,
    check: bool = True,
    output: str | TextIO | None = None,
    extra_params: dict[str, Any] | None = None,
    checks: list[tuple[str, CHECKTYPE]] | None = None,
    ignore_unknowns: bool = False,
    default_values: list[tuple[str, CONVERTER]] | None = None,
    convert: dict[str, Callable[[Any], Any]] | None = None,
    asgi: bool = False,
    exclusive: bool = False,
) -> str:
    """Generate an nginx configuration for application."""
    from jinja2 import UndefinedError

    from ..config import get_config

    if args is None:
        args = []

    if application_dir is None:
        msg = "no application directory"
        raise click.BadParameter(msg)

    if help_args is None:
        help_args = NGINX_ARGS

    convert = {"root": topath} if convert is None else {"root": topath, **convert}

    application_dir = topath(application_dir)
    template = get_template(template_name or "nginx.conf", application_dir)

    known = get_known(help_args) | {"staticdirs", "toplevel", "favicon", "error_pages"}
    # directory to match with / for say /favicon.ico
    root_location_match = None
    params: dict[str, Any] = {}
    try:
        # arguments from .flaskenv
        params = {k: v for k, v in footprint_config(application_dir).items() if k in known}
        params.update(fix_params(args, convert))
        if extra_params:
            params.update(extra_params)

        prefix = params.get("prefix", "")
        if "root" in params:
            root = str(topath(application_dir / str(params["root"])))
            params["root"] = root
            rp = params.get("root_prefix")
            staticdirs = [StaticFolder(rp if rp is not None else prefix, root, rewrite=False)]
        else:
            staticdirs = []
        # if the params have an app value use that as the entrypoint
        entrypoint = params.get("app")
        if entrypoint is None:
            entrypoint = get_app_entrypoint(application_dir, asgi=asgi)
        routes = []
        if entrypoint != "@none":
            app = find_application(entrypoint, str(application_dir))
            staticdirs.extend(
                get_static_folders_for_app(
                    app,
                    prefix=prefix,
                ),
            )
            if exclusive:
                routes = get_route_prefixes(app)  # just to check it works
                routes = [fix_path(r) for r in routes if r and r != "/"]
                if prefix:
                    routes = [f"{prefix[1:]}/{r}" for r in routes]
                click.secho(
                    f"Warning: exclusive routes: ^/({'|'.join(routes)})",
                    err=True,
                    fg="yellow",
                    bold=True,
                )

        error_pages = list(has_error_page(staticdirs, error_pages=[401, 403, 404, 500]))
        params["error_pages"] = error_pages
        params["staticdirs"] = staticdirs
        for s in staticdirs:
            if not s.url:  # top level?
                root_location_match = url_match(s.folder)
        # need a root directory for server
        if "root" not in params and not staticdirs:
            params["root"] = topath(application_dir)
        # add any defaults
        defaults: list[tuple[str, CONVERTER]] = [
            ("application_dir", lambda _: application_dir),
            ("appname", appname_func),
            ("root", lambda _: staticdirs[0].folder),
            ("server_name", lambda _: server_name),
        ]

        if default_values:
            defaults.extend(default_values)

        for key, default_func in defaults:
            if key not in params:
                v = default_func(params)
                if v is not None:
                    params[key] = v

        def isint(s: str | int) -> bool:
            return isinstance(s, int) or s.isdigit()

        if "host" in params:
            h = params["host"]
            if isint(h):
                params["host"] = "127.0.0.1"
                params["port"] = h
            elif ":" in h:
                s, h = h.rsplit(":", maxsplit=1)
                params["host"] = s
                params["port"] = h

        if "port" not in params:
            params["port"] = 8000

        if root_location_match is not None and "root_location_match" not in params:
            params["root_location_match"] = root_location_match
        if "toplevel" not in params and not root_location_match:
            d = find_toplevel(str(application_dir))
            if d:
                params["toplevel"] = str(topath(application_dir / d))

        if "toplevel" in params:
            params["toplevel"] = str(topath(params["toplevel"]))

        if check:
            msg = check_app_dir(str(application_dir))
            if msg:
                raise click.BadParameter(msg, param_hint="application_dir")

            if not ignore_unknowns:
                extra = set(params) - known
                if extra:
                    msg = f"unknown arguments {extra}"
                    raise click.BadParameter(
                        msg,
                        param_hint="params",
                    )
            failed: list[str] = []
            checks = (checks or []) + [
                to_check_func("root", isdir, '"{root}" is not a directory'),
                to_check_func("toplevel", isdir, '"{toplevel}" is not a directory'),
            ]
            for key, func in checks:
                if key in params:
                    v = params[key]
                    msg = func(key, v)
                    if msg is not None:
                        click.secho(
                            msg,
                            fg="yellow",
                            bold=True,
                            err=True,
                        )
                        failed.append(key)
                if failed:
                    raise click.Abort

        res = template.render(Config=get_config(), routes=routes, **params)
        to_output(res, output)
    except UndefinedError as e:
        undefined_error(e, template, params)
        raise click.Abort from e
    return res


# pylint: disable=too-many-locals too-many-branches
@config.command(name="nginx", help=NGINX_HELP)
@template_option
@config_options
@click.option(
    "--no-static",
    is_flag=True,
    help="Don't try to introspect static files. (Useful for non-flask websites)",
)
@asgi_option
@click.option(
    "-x",
    "--404",
    "exclude_urls",
    type=click.Path(exists=True, dir_okay=False, file_okay=True, path_type=Path),
    help="""list of urls to immediately return 404 for (one per line)""",
)
@click.option(
    "--exclusive",
    is_flag=True,
    help="""add a negative assertion to the known urls of the app.
 (Caution you can't add any new routes to the app after this)""",
)
@click.option(
    "-d",
    "--app-dir",
    "application_dir",
    type=click.Path(exists=True, dir_okay=True, file_okay=False, path_type=Path),
    help="""location of repo or current directory""",
)
@click.argument("server_name")
@click.argument("params", nargs=-1)
def nginx_cmd(  # noqa: PLR0917
    application_dir: Path | None,
    server_name: str,
    template: str | None,
    exclude_urls: Path | None,
    params: list[str],
    output: str | None,
    *,
    asgi: bool,
    no_check: bool,
    no_static: bool = False,
    exclusive: bool = False,
) -> None:
    """Generate nginx config file.

    PARAMS are key=value arguments for the template.
    """
    # pylint: disable=line-too-long
    # see https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-20-04
    # place this in /etc/systemd/system/
    params = list(params)
    if no_static:
        params.append("app=@none")

    urls = []
    if exclude_urls:
        with exclude_urls.open("r", encoding="utf-8") as fp:
            for line in fp:
                line = line.strip()
                if line and line.startswith("/"):
                    urls.append(re.escape(line[1:]))
    nginx(
        application_dir or Path.cwd(),
        server_name,
        params,
        template_name=template,
        check=not no_check,
        output=output,
        asgi=asgi,
        extra_params={"exclude_urls": urls},
        exclusive=exclusive,
    )


@config.command(name="nginx-run-app", hidden=True)
@click.option("-p", "--port", default=5000, help="port to listen", show_default=True)
@click.option(
    "-x",
    "--no-start",
    "no_start_app",
    is_flag=True,
    help="don't start the website in background",
    show_default=True,
)
@click.option(
    "--entrypoint",
    help="web application entrypoint",
)
@asgi_option
@click.option("--browse", is_flag=True, help="open web application in browser")
@click.option(
    "-d",
    "--app-dir",
    "application_dir",
    type=click.Path(exists=True, dir_okay=True, file_okay=False),
    help="""location of repo or current directory""",
)
def nginx_run_app_cmd(
    application_dir: Path | None,
    port: int,
    entrypoint: str | None,
    *,
    asgi: bool,
    no_start_app: bool = False,
    browse: bool = False,
) -> None:
    """Run nginx as a non daemon process with web app in background."""
    import signal
    import uuid
    from tempfile import gettempdir

    from ..utils import browser, require_mod

    nginx_exe = which("nginx")

    if not no_start_app:
        if asgi:
            require_mod("uvicorn")
        else:
            require_mod("gunicorn")

    if application_dir is None:
        application_dir = Path.cwd()

    application_dir = topath(application_dir)
    tmplt = get_template("nginx-test.conf", application_dir)
    res = tmplt.render(  # pylint: disable=no-member
        application_dir=application_dir,
        port=port,
    )
    tmpfile = Path(gettempdir()) / f"nginx-{uuid.uuid4()}.conf"

    url = f"http://127.0.0.1:{port}"
    click.secho(f"listening on {url}", fg="green", bold=True)
    running: subprocess.Popen[bytes] | None = None
    brws: Thread | None = None
    try:
        with tmpfile.open("wt", encoding="utf-8") as fp:
            fp.write(res)

        if not no_start_app:
            app_entry = entrypoint or get_app_entrypoint(application_dir, asgi=asgi)
            running = run_app(
                application_dir,
                f"unix:{application_dir}/app.sock",
                app_entry,
                asgi=asgi,
            )
        else:
            click.secho(
                f"expecting app running in {application_dir} with app.sock as unix socket",
                fg="magenta",
                bold=True,
            )
        if browse:
            brws = browser(url=url)

        subprocess.check_call([nginx_exe, "-c", str(tmpfile)])

    finally:
        tmpfile.unlink(missing_ok=True)
        if running is not None:
            os.kill(running.pid, signal.SIGINT)
        if brws is not None:
            brws.join()


@config.command(name="nginx-run")
@click.option(
    "-p",
    "--port",
    default=5000,
    help="port for nginx to listen",
    show_default=True,
)
@click.option(
    "-u",
    "--upload-max",
    default="40M",
    help="""maximum file upload size possible.
    (if you try to upload more than this you will get mysterious permission denied errors to `/var/lib/nginx/body`)""",
    show_default=True,
)
@click.option(
    "--entrypoint",
    help="web application entrypoint. If not specified will try to find it in the application directory",
)
@asgi_option
@click.option("--browse", is_flag=True, help="open web application in browser")
@click.option(
    "-d",
    "--app-dir",
    "application_dir",
    type=click.Path(exists=True, dir_okay=True, file_okay=False, path_type=Path),
    help="""location of repo or current directory""",
)
@click.argument("nginxfile", type=click.File("rt", encoding="utf-8"), required=True)
@click.argument("server_args", nargs=-1)
def nginx_run_cmd(  # noqa: C901, PLR0915, PLR0917
    nginxfile: IO[str],
    application_dir: Path | None,
    entrypoint: str | None,
    port: int,
    upload_max: str,
    server_args: tuple[str, ...],
    *,
    browse: bool,
    asgi: bool,
) -> None:
    """Run nginx as a non daemon process using the specified nginxfile.

    This will test the generated nginx configuration file (especially the delivery of static files
    and 404 errors).
    """
    import signal
    from tempfile import NamedTemporaryFile

    from ..utils import browser, has_mod

    nginx_exe = which("nginx")
    if asgi:
        if not has_mod("uvicorn"):
            if not has_mod("gunicorn"):
                click.secho(
                    "neither `uvicorn` nor `gunicorn` is installed. Please install one of them.",
                    err=True,
                    fg="red",
                )
                raise click.Abort
            click.secho("maybe not an `--asgi` application?", err=True)
            raise click.Abort
    elif not has_mod("gunicorn"):
        if not has_mod("uvicorn"):
            click.secho(
                "neither `gunicorn` nor `uvicorn` is installed. Please install one of them.",
                err=True,
                fg="red",
            )
            raise click.Abort
        click.secho("maybe an `--asgi` application?", err=True)
        raise click.Abort

    def once(m: str) -> Callable[[re.Match[str]], str]:
        done = False

        def f(_r: re.Match[str]) -> str:
            nonlocal done
            if done:
                return ""
            done = True
            return m

        return f

    def get_server() -> tuple[str, str | None]:
        """Parse nginx.conf file for server and host."""
        access_re = re.compile("access_log [^;]+;")  # remove access log entries
        # see comment in nginx-app.conf about client_body_buffer_size and client_max_body_size
        max_body_re = re.compile("(client_max_body_size|client_body_buffer_size) [^;]+;")
        listen_re = re.compile("listen [^;]+;")  # replace listen {port}; with our port
        proxy_pass_re = re.compile(
            r"proxy_pass\s+http://([^\s]+)/?\s*;",
        )  # find where the proxy app.sock is..
        # search for say:
        #    upstream app {
        #        server unix:{{application_dir}}/app.sock fail_timeout=0;
        #    } # noqa: ERA001
        server_re = re.compile(r"server\s+([^{\s]+)/?.*;")

        server = nginxfile.read()
        # remove old access_log and replace listen commands
        server = access_re.sub("", server)
        server = max_body_re.sub("", server)
        server = listen_re.sub(once(f"listen {port};"), server)
        # find unix socket locations
        m = server_re.search(server) or proxy_pass_re.search(server)
        bind = None if not m else m.group(1)
        return server, bind

    template: Template = get_template("nginx-app.conf", application_dir)
    server, bind = get_server()
    if not bind or not bind.startswith("unix:"):
        click.secho("can't find unix: socket entrypoint in file", err=True, fg="red")
        raise click.Abort
    application_dir = application_dir or Path.cwd()
    entry = entrypoint or get_app_entrypoint(application_dir, asgi=asgi)
    nginx_conf = template.render(server=server, upload_max=upload_max)
    threads: list[threading.Thread] = []

    with NamedTemporaryFile("w") as fp:
        fp.write(nginx_conf)
        fp.flush()
        url = f"http://127.0.0.1:{port}"
        click.secho(f"listening on {url}", fg="green", bold=True)
        app = run_app(application_dir, bind, entry, asgi=asgi, args=server_args)

        if browse:
            threads.append(browser(url))
        try:
            subprocess.run([nginx_exe, "-c", fp.name], check=False)
        finally:
            os.kill(app.pid, signal.SIGINT)
            for thrd in threads:
                thrd.join(timeout=2.0)


@config.command(name="nginx-install")
@click.option(
    "--check-only",
    default=True,
    is_flag=True,
    help="check if nginx differs from existing config",
)
@click.argument(
    "nginxfile",
    type=click.Path(exists=True, dir_okay=False, file_okay=True),
)
def nginx_install_cmd(nginxfile: str, *, check_only: bool) -> None:
    """Install nginx config file."""
    # install frontend
    conf = nginx_install(nginxfile, check_only=check_only)
    if not check_only:
        if conf is None:
            raise click.Abort

        click.secho(f"{conf} installed!", fg="green", bold=True)


@config.command(name="nginx-uninstall")
@click.argument("nginxfile")
def nginx_uninstall_cmd(nginxfile: str) -> None:
    """Uninstall nginx config file."""
    nginx_uninstall(nginxfile)

    click.secho(f"{nginxfile} uninstalled!", fg="green", bold=True)


@config.command(name="nginx-ssl", hidden=True)
@click.option("--days", default=365, help="days of validity")
@click.argument(
    "server_name",
    required=True,
)
def nginx_ssl_cmd(server_name: str, days: int = 365) -> None:
    """Generate openssl TLS self-signed key for a website."""
    ssl_dir = "/etc/ssl"
    openssl = which("openssl")
    sudo = which("sudo")

    country = server_name.rsplit(".", maxsplit=1)[-1].upper()

    cmd = [
        sudo,
        openssl,
        "req",
        "-x509",
        "-noenc",
        "-days",
        str(days),
        "-newkey",
        "rsa:4096",
        "-keyout",
        f"{ssl_dir}/private/{server_name}.key",
        "-out",
        f"{ssl_dir}/certs/{server_name}.pem",
        "-subj",
        f"/C={country}/CN={server_name}",
    ]

    subprocess.run(cmd, check=True)
    click.secho(f"written keys for {server_name} to {ssl_dir}", fg="green")
