from __future__ import annotations

import os
import re
import subprocess
import sys
from os.path import isdir
from os.path import join
from os.path import split
from pathlib import Path
from typing import Any
from typing import Callable
from typing import IO
from typing import TextIO
from typing import TYPE_CHECKING

import click

from ..core import find_application
from ..core import get_app_entrypoint
from ..core import get_route_prefixes
from ..core import get_static_folders_for_app
from ..core import StaticFolder
from ..core import topath
from ..templating import get_template
from ..templating import undefined_error
from ..utils import which
from .cli import config
from .utils import asgi_option
from .utils import check_app_dir
from .utils import CHECKTYPE
from .utils import config_options
from .utils import CONVERTER
from .utils import find_toplevel
from .utils import fix_params
from .utils import footprint_config
from .utils import get_known
from .utils import has_error_page
from .utils import make_args
from .utils import template_option
from .utils import to_check_func
from .utils import to_output
from .utils import url_match

if TYPE_CHECKING:
    from jinja2 import Template


def run_app(
    application_dir: str,
    bind: str,
    app: str = "app.app",
    *,
    asgi: bool = False,
    args: tuple[str, ...] = (),
) -> subprocess.Popen[bytes]:

    if asgi:
        assert bind.startswith("unix:"), bind
        bind = bind[len("unix:") :]
        exe = "uvicorn"

        cmd = [
            sys.executable,
            "-m",
            "uvicorn",
            "--proxy-headers",
            f"--uds={bind}",
            *args,
            app,
        ]

    else:
        exe = "gunicorn"
        cmd = [
            sys.executable,
            "-m",
            "gunicorn",
            "--access-logfile=-",
            "--error-logfile=-",
            "--bind",
            bind,
            *args,
            app,
        ]

    click.secho(
        f"starting {exe} in {topath(application_dir)}",
        fg="green",
        bold=True,
    )

    click.secho(" ".join(cmd), fg="green")
    # subprocess.run(cmd, cwd=application_dir, env=os.environ, check=True)
    return subprocess.Popen(cmd, cwd=application_dir, env=os.environ)


def patch_nginx_conf(oldfile: Path, newfile: Path) -> Path:
    newlines: list[str] = []
    active: bool = False
    with newfile.open("rt", encoding="utf-8") as fp:
        for line in fp:
            if line.lstrip().startswith("# >>> generated by footprint"):
                active = True
            elif line.lstrip().startswith("# <<< generated by footprint"):
                break
            elif active:
                newlines.append(line)
    if not newlines:
        return newfile
    nnewfile = newfile.parent / f"{newfile.stem}-patched{newfile.suffix}"
    certbot = "# managed by Certbot" in oldfile.read_text(encoding="utf-8")
    with nnewfile.open("wt", encoding="utf-8") as fp:
        patched = False
        active = False

        with oldfile.open("rt", encoding="utf-8") as olfp:
            for line in olfp:
                if line.lstrip().startswith("# >>> generated by footprint"):
                    active = True
                    fp.write(line)
                    for newline in newlines:
                        if certbot and newline.lstrip().startswith("listen"):
                            continue
                        fp.write(newline)
                    patched = True
                elif line.lstrip().startswith("# <<< generated by footprint"):
                    active = False
                    fp.write(line)
                elif not active:
                    fp.write(line)
    return nnewfile if patched else newfile


def nginx_install(nginxconf: str) -> str | None:
    import filecmp
    from ..config import get_config

    nginxfile = Path(nginxconf)

    Config = get_config()

    conf = nginxfile.name
    # Ubuntu, RHEL8
    for td in Config.nginx_dirs:
        targetd = Path(td)
        if targetd.is_dir():
            break
    else:
        raise RuntimeError("can't find nginx configuration directory")
    sudo = which("sudo")
    systemctl = which("systemctl")

    def sudocmd(*args: Any, check: bool = True) -> subprocess.CompletedProcess[bytes]:
        return subprocess.run([sudo] + [str(a) for a in args], check=check)

    def runcmd(*args: Any, check: bool = True) -> subprocess.CompletedProcess[bytes]:
        return subprocess.run([str(a) for a in args], check=check)

    def systemctlcmd(*args: Any, check: bool = True) -> int:
        return subprocess.run(
            [sudo, systemctl] + [str(a) for a in args],
            check=check,
        ).returncode

    conffile = targetd / conf

    exists = conffile.is_file()
    if not exists or not filecmp.cmp(conffile, nginxfile):
        bak = None
        if exists:
            bak = nginxfile.parent / f"{conffile.name}.bak"
            runcmd("cp", conffile, bak)
            # file might have been patched by certbot or other tools so we need to patch it
            nnginxfile = patch_nginx_conf(conffile, nginxfile)
            if filecmp.cmp(conffile, nnginxfile):
                click.secho(f"nginx file {conf} unchanged", fg="green")
                if bak is not None:
                    bak.unlink(missing_ok=True)
                return conf
            click.secho(f"warning: overwriting old {conf}", fg="yellow")
            sudocmd("cp", nnginxfile, conffile)
        else:
            sudocmd("cp", nginxfile, conffile)

        if sudocmd("nginx", "-t", check=False).returncode != 0:
            sudocmd("rm", conffile)
            if bak is not None:
                sudocmd("mv", bak, conffile)
            click.secho("nginx configuration faulty", fg="red", err=True)
            return None if bak is None else conf
        if bak is not None:
            bak.unlink(missing_ok=True)

        systemctlcmd("restart", "nginx")
    else:
        click.secho(f"nginx file {conf} unchanged", fg="green")
    return conf


def nginx_uninstall(nginxconf: str) -> None:
    from ..config import get_config

    Config = get_config()
    nginxfile = Path(nginxconf)
    conf = nginxfile.name
    if "." not in conf:
        conf += ".conf"
    sudo = which("sudo")
    systemctl = which("systemctl")

    def sudocmd(*args: str, check: bool = True) -> subprocess.CompletedProcess[bytes]:
        return subprocess.run([sudo] + list(args), check=check)

    def systemctlcmd(*args: str, check: bool = True) -> int:
        return subprocess.run([sudo, systemctl] + list(args), check=check).returncode

    for d in Config.nginx_dirs:
        fname = Path(d) / conf
        if fname.is_file():
            sudocmd("rm", str(fname))
            systemctlcmd("restart", "nginx.service")
            return

    click.secho(f"no nginx file {nginxfile}", fg="yellow", err=True)


NGINX_ARGS = {
    "server_name": "name of website",
    "application_dir": "locations of repo",
    "app": "entrypoint to app",
    "appname": "application name [default: directory name]",
    "root": "static files root directory",
    "root_prefix": "location prefix to use (only used if root is defined)",
    "prefix": "url prefix for application [default: /]",
    "expires": "expires header for static files [default: off] e.g. 30d",
    "listen": "listen on port [default: 80]",
    "host": "proxy to a port [default: use unix socket]",
    "port": "TCP/IP port to use",
    "root_location_match": "regex for matching static directory files",
    "access_log": "'on' or 'off'. log static asset requests [default:off]",
    "extra": "extra (legal) nginx commands for proxy",
    "ssl": "create an secure server configuration [see nginx-ssl]",
    "log_format": "specify the log_format",
    "authentication": "authentication file",
    "exclude_urls": "list of urls to immediately return 404 for (one per line)",
}

NGINX_HELP = f"""
Generate a nginx conf file for website.

Use footprint config nginx website ... etc.
with the following arguments:

\b
{make_args(NGINX_ARGS)}
\b
example:
\b
footprint config nginx mcms.plantenergy.edu.au access-log=on
\b
"""


def appname_func(params: dict[str, Any]) -> str:
    app = str(params["application_dir"])
    return str(split(app)[-1])


def nginx(  # noqa: C901
    application_dir: str,
    server_name: str,
    args: list[str] | None = None,
    *,
    template_name: str | None = None,
    help_args: dict[str, str] | None = None,
    check: bool = True,
    output: str | TextIO | None = None,
    extra_params: dict[str, Any] | None = None,
    checks: list[tuple[str, CHECKTYPE]] | None = None,
    ignore_unknowns: bool = False,
    default_values: list[tuple[str, CONVERTER]] | None = None,
    convert: dict[str, Callable[[Any], Any]] | None = None,
    ssl: bool = False,
    asgi: bool = False,
    exclusive: bool = False,
) -> str:
    """Generate an nginx configuration for application"""
    from ..config import get_config
    from jinja2 import UndefinedError

    if args is None:
        args = []

    if application_dir is None:
        raise click.BadParameter("no application directory")

    if help_args is None:
        help_args = NGINX_ARGS

    if convert is None:
        convert = {"root": topath}
    else:
        convert = {"root": topath, **convert}

    application_dir = topath(application_dir)
    template = get_template(template_name or "nginx.conf", application_dir)

    known = get_known(help_args) | {"staticdirs", "toplevel", "favicon", "error_pages"}
    # directory to match with / for say /favicon.ico
    root_location_match = None
    params: dict[str, Any] = {}
    try:
        # arguments from .flaskenv
        params = {
            k: v for k, v in footprint_config(application_dir).items() if k in known
        }
        params.update(fix_params(args, convert))
        if extra_params:
            params.update(extra_params)

        prefix = params.get("prefix", "")
        if "root" in params:
            root = topath(join(application_dir, str(params["root"])))
            params["root"] = root
            rp = params.get("root_prefix", None)
            staticdirs = [StaticFolder(rp if rp is not None else prefix, root, False)]
        else:
            staticdirs = []
        # if the params have an app value use that as the entrypoint
        entrypoint = params.get("app", None)
        if entrypoint is None:
            entrypoint = get_app_entrypoint(application_dir, asgi=asgi)
        routes = []
        if entrypoint != "@none":
            app = find_application(entrypoint, application_dir)
            staticdirs.extend(
                get_static_folders_for_app(
                    app,
                    prefix=prefix,
                ),
            )
            if exclusive:
                routes = get_route_prefixes(app)  # just to check it works
                routes = [
                    r[1:] if r.startswith("/") else r for r in routes if r and r != "/"
                ]
                if prefix:
                    routes = [f"{prefix[1:]}/{r}" for r in routes]
                click.secho(
                    f"Warning: exclusive routes: ^/({'|'.join(routes)})",
                    err=True,
                    fg="yellow",
                    bold=True,
                )

        error_pages = list(has_error_page(staticdirs, error_pages=[401, 403, 404, 500]))
        params["error_pages"] = error_pages
        params["staticdirs"] = staticdirs
        for s in staticdirs:
            if not s.url:  # top level?
                root_location_match = url_match(s.folder)
        # need a root directory for server
        if "root" not in params and not staticdirs:
            params["root"] = topath(application_dir)
            # raise click.BadParameter("no root directory found", param_hint="params")
        # add any defaults
        defaults: list[tuple[str, CONVERTER]] = [
            ("application_dir", lambda _: application_dir),
            ("appname", appname_func),
            ("root", lambda _: staticdirs[0].folder),
            ("server_name", lambda _: server_name),
            ("ssl", lambda _: ssl),
        ]

        if default_values:
            defaults.extend(default_values)

        for key, default_func in defaults:
            if key not in params:
                v = default_func(params)
                if v is not None:
                    params[key] = v

        def isint(s: str | int) -> bool:
            return isinstance(s, int) or s.isdigit()

        if "host" in params:
            h = params["host"]
            if isint(h):
                params["host"] = "127.0.0.1"
                params["port"] = h
            else:
                if ":" in h:
                    s, h = h.rsplit(":", maxsplit=1)
                    params["host"] = s
                    params["port"] = h

        if "port" not in params:
            params["port"] = 8000

        if root_location_match is not None and "root_location_match" not in params:
            params["root_location_match"] = root_location_match
        if "toplevel" not in params and not root_location_match:
            d = find_toplevel(application_dir)
            if d:
                params["toplevel"] = topath(join(application_dir, d))

        if "toplevel" in params:
            params["toplevel"] = topath(params["toplevel"])

        if check:
            msg = check_app_dir(application_dir)
            if msg:
                raise click.BadParameter(msg, param_hint="application_dir")

            if not ignore_unknowns:
                extra = set(params) - known
                if extra:
                    raise click.BadParameter(
                        f"unknown arguments {extra}",
                        param_hint="params",
                    )
            failed: list[str] = []
            checks = (checks or []) + [
                to_check_func("root", isdir, '"{root}" is not a directory'),
                to_check_func("toplevel", isdir, '"{toplevel}" is not a directory'),
            ]
            for key, func in checks:
                if key in params:
                    v = params[key]
                    msg = func(key, v)
                    if msg is not None:
                        click.secho(
                            msg,
                            fg="yellow",
                            bold=True,
                            err=True,
                        )
                        failed.append(key)
                if failed:
                    raise click.Abort()

        res = template.render(Config=get_config(), routes=routes, **params)
        to_output(res, output)
        return res
    except UndefinedError as e:
        undefined_error(e, template, params)
        raise click.Abort()


# pylint: disable=too-many-locals too-many-branches
@config.command(name="nginx", help=NGINX_HELP)  # noqa: C901
@template_option
@config_options
@click.option("--ssl", is_flag=True, help="make it secure")
@click.option(
    "--no-static",
    is_flag=True,
    help="Don't try to introspect static files. (Useful for non-flask websites)",
)
@asgi_option
@click.option(
    "-x",
    "--404",
    "exclude_urls",
    type=click.Path(exists=True, dir_okay=False, file_okay=True),
    help="""list of urls to immediately return 404 for (one per line)""",
)
@click.option(
    "--exclusive",
    is_flag=True,
    help="""add a negative assertion to the known urls of the app. (Caution you can't add any new routes to the app after this)""",
)
@click.option(
    "-d",
    "--app-dir",
    "application_dir",
    type=click.Path(exists=True, dir_okay=True, file_okay=False),
    help="""location of repo or current directory""",
)
@click.argument("server_name")
@click.argument("params", nargs=-1)
def nginx_cmd(
    application_dir: str | None,
    server_name: str,
    template: str | None,
    asgi: bool,
    exclude_urls: str | None,
    params: list[str],
    no_check: bool,
    output: str | None,
    ssl: bool = False,
    no_static: bool = False,
    exclusive: bool = False,
) -> None:
    """Generate nginx config file.

    PARAMS are key=value arguments for the template.
    """
    # pylint: disable=line-too-long
    # see https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-20-04
    # place this in /etc/systemd/system/
    params = list(params)
    if no_static:
        params.append("app=@none")

    urls = []
    if exclude_urls:
        with open(exclude_urls, encoding="utf-8") as fp:
            for line in fp:
                line = line.strip()
                if line and line.startswith("/"):
                    urls.append(line[1:].replace(".", r"\."))
    nginx(
        application_dir or ".",
        server_name,
        params,
        template_name=template,
        check=not no_check,
        output=output,
        ssl=ssl,
        asgi=asgi,
        extra_params={"exclude_urls": urls},
        exclusive=exclusive,
    )


@config.command(name="nginx-run-app")
@click.option("-p", "--port", default=5000, help="port to listen", show_default=True)
@click.option(
    "-x",
    "--no-start",
    "no_start_app",
    is_flag=True,
    help="don't start the website in background",
    show_default=True,
)
@click.option(
    "--entrypoint",
    help="web application entrypoint",
)
@asgi_option
@click.option("--browse", is_flag=True, help="open web application in browser")
@click.option(
    "-d",
    "--app-dir",
    "application_dir",
    type=click.Path(exists=True, dir_okay=True, file_okay=False),
    help="""location of repo or current directory""",
)
def nginx_run_app_cmd(
    application_dir: str | None,
    port: int,
    entrypoint: str | None,
    asgi: bool,
    no_start_app: bool = False,
    browse: bool = False,
) -> None:
    """Run nginx as a non daemon process with web app in background."""
    import signal
    import uuid
    from threading import Thread

    from tempfile import gettempdir

    from ..utils import browser, require_mod

    nginx_exe = which("nginx")

    if not no_start_app:
        if asgi:
            require_mod("uvicorn")
        else:
            require_mod("gunicorn")

    if application_dir is None:
        application_dir = "."

    application_dir = topath(application_dir)
    tmplt = get_template("nginx-test.conf", application_dir)
    res = tmplt.render(  # pylint: disable=no-member
        application_dir=application_dir,
        port=port,
    )
    tmpfile = Path(gettempdir()) / f"nginx-{uuid.uuid4()}.conf"

    url = f"http://127.0.0.1:{port}"
    click.secho(f"listening on {url}", fg="green", bold=True)
    running: subprocess.Popen[bytes] | None = None
    brws: Thread | None = None
    try:
        with tmpfile.open("wt", encoding="utf-8") as fp:
            fp.write(res)

        if not no_start_app:
            app_entry = entrypoint or get_app_entrypoint(application_dir, asgi=asgi)
            running = run_app(
                application_dir,
                f"unix:{application_dir}/app.sock",
                app_entry,
                asgi=asgi,
            )
        else:
            click.secho(
                f"expecting app running in {application_dir} with app.sock as unix socket",
                fg="magenta",
                bold=True,
            )
        if browse:
            brws = browser(url=url)

        subprocess.check_call([nginx_exe, "-c", str(tmpfile)])

    finally:
        tmpfile.unlink(missing_ok=True)
        if running is not None:
            os.kill(running.pid, signal.SIGINT)
        if brws is not None:
            brws.join()
        # os.system("stty sane")


@config.command(name="nginx-run")
@click.option(
    "-p",
    "--port",
    default=5000,
    help="port for nginx to listen",
)
@click.option(
    "--entrypoint",
    help="web application entrypoint",
)
@asgi_option
@click.option("--browse", is_flag=True, help="open web application in browser")
@click.argument("nginxfile", type=click.File("rt", encoding="utf-8"))
@click.option(
    "-d",
    "--app-dir",
    "application_dir",
    type=click.Path(exists=True, dir_okay=True, file_okay=False),
    help="""location of repo or current directory""",
)
@click.argument("server_args", nargs=-1)
def nginx_run_cmd(
    nginxfile: IO[str],
    application_dir: str | None,
    entrypoint: str | None,
    port: int,
    browse: bool,
    asgi: bool,
    server_args: tuple[str, ...],
) -> None:
    """Run nginx as a non daemon process using generated app config file.

    This will test the generated nginx configuration file (especially the delivery of static files).
    """
    import signal
    import threading
    from tempfile import NamedTemporaryFile

    from ..utils import browser, require_mod

    nginx_exe = which("nginx")
    if asgi:
        require_mod("uvicorn")
    else:
        require_mod("gunicorn")

    def once(m: str) -> Callable[[re.Match[str]], str]:
        done = False

        def f(r: re.Match[str]) -> str:
            nonlocal done
            if done:
                return ""
            done = True
            return m

        return f

    def get_server() -> tuple[str, str | None]:
        """parse nginx.conf file for server and host"""

        A = re.compile("access_log [^;]+;")  # remove access log entries
        L = re.compile("listen [^;]+;")  # replace listen {port}; with our port
        H = re.compile(
            r"proxy_pass\s+http://([^\s]+)/?\s*;",
        )  # find where the proxy app.sock is..
        # search for say:
        #    upstream app {
        #        server unix:{{application_dir}}/app.sock fail_timeout=0;
        #    }
        S = re.compile(r"server\s+([^{\s]+)/?.*;")

        server = nginxfile.read()
        # remove old access_log and replace listen commands
        server = A.sub("", server)
        server = L.sub(once(f"listen {port};"), server)
        # find unix socket locations
        m = S.search(server) or H.search(server)
        return server, None if not m else m.group(1)

    template: Template = get_template("nginx-app.conf", application_dir)
    server, bind = get_server()
    if not bind or not bind.startswith("unix:"):
        click.secho("can't find unix: socket entrypoint in file", err=True, fg="red")
        raise click.Abort()
    application_dir = application_dir or "."

    res = template.render(server=server)
    threads: list[threading.Thread] = []

    with NamedTemporaryFile("w") as fp:
        fp.write(res)
        fp.flush()
        url = f"http://127.0.0.1:{port}"
        click.secho(f"listening on {url}", fg="green", bold=True)

        entry = entrypoint or get_app_entrypoint(application_dir, asgi=asgi)
        app = run_app(application_dir, bind, entry, asgi=asgi, args=server_args)

        if browse:
            threads.append(browser(url))
        try:
            subprocess.run([nginx_exe, "-c", fp.name], check=False)
        finally:
            os.kill(app.pid, signal.SIGINT)
            for thrd in threads:
                thrd.join(timeout=2.0)
            # os.system("stty sane")


@config.command(name="nginx-install")
@click.argument(
    "nginxfile",
    type=click.Path(exists=True, dir_okay=False, file_okay=True),
)
def nginx_install_cmd(nginxfile: str) -> None:
    """Install nginx config file."""

    # install frontend
    conf = nginx_install(nginxfile)
    if conf is None:
        raise click.Abort()

    click.secho(f"{conf} installed!", fg="green", bold=True)


@config.command(name="nginx-uninstall")
@click.argument("nginxfile")
def nginx_uninstall_cmd(nginxfile: str) -> None:
    """Uninstall nginx config file."""

    nginx_uninstall(nginxfile)

    click.secho(f"{nginxfile} uninstalled!", fg="green", bold=True)


@config.command(name="nginx-ssl", hidden=True)
@click.option("--days", default=365, help="days of validity")
@click.argument(
    "server_name",
    required=True,
)
def nginx_ssl_cmd(server_name: str, days: int = 365) -> None:
    """Generate openssl TLS self-signed key for a website"""

    ssl_dir = "/etc/ssl"
    openssl = which("openssl")
    sudo = which("sudo")

    country = server_name.split(".")[-1].upper()

    cmd = [
        sudo,
        openssl,
        "req",
        "-x509",
        "-noenc",
        "-days",
        str(days),
        "-newkey",
        "rsa:4096",
        "-keyout",
        f"{ssl_dir}/private/{server_name}.key",
        "-out",
        f"{ssl_dir}/certs/{server_name}.pem",
        "-subj",
        f"/C={country}/CN={server_name}",
    ]

    subprocess.run(cmd, check=True)
    click.secho(f"written keys for {server_name} to {ssl_dir}", fg="green")
