from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from os.path import isdir, split
from pathlib import Path
from typing import IO, TYPE_CHECKING, Any

import click

from ..core import StaticFolder, introspect
from ..templating import get_template, undefined_error
from ..utils import footprint_config, get_app_entrypoint, has_mod, topath, which
from .cli import config
from .utils import (
    CHECKTYPE,
    CONVERTER,
    app_dir_option,
    asgi_option,
    check_app_dir,
    config_options,
    find_toplevel,
    find_webserver,
    fix_params,
    get_known,
    has_error_page,
    ignore_unknowns_option,
    make_args,
    python_executable_option,
    template_option,
    to_check_func,
    to_output,
    url_match,
    webserver_option,
)

if TYPE_CHECKING:
    import threading
    from collections.abc import Callable

    from jinja2 import Template


def ensure_package(exe: str, python_executable: str | None = None) -> None:
    if not has_mod(exe, python_executable):
        click.secho(
            f"{exe} is not installed. Please install it with `pip install {exe}`",
            fg="red",
            bold=True,
            err=True,
        )
        raise click.Abort


def run_app(
    application_dir: Path,
    bind: str,
    entrypoint: str,
    *,
    asgi: bool,
    webserver: str,  # Literal["uvicorn", "hypercorn", "gunicorn"],
    args: tuple[str, ...] = (),
    python_executable: str | None = None,
) -> subprocess.Popen[bytes]:

    if python_executable is None:
        python_executable = sys.executable

    if asgi:
        if webserver == "uvicorn":
            if bind.startswith("unix:"):
                binds = [f"--uds={bind[len('unix:') :]}"]
            else:
                host, port = bind.split(":", maxsplit=1)
                binds = [f"--host={host}", f"--port={port}"]
            exe = "uvicorn"
            cmd = [
                python_executable,
                "-m",
                exe,
                "--proxy-headers",
                *binds,
                *args,
                entrypoint,
            ]
        elif webserver == "hypercorn":
            exe = "hypercorn"
            cmd = [
                python_executable,
                "-m",
                exe,
                "--bind",
                bind,
                "--access-logfile=-",
                "--error-logfile=-",
                *args,
                entrypoint,
            ]
        else:  # webserver == "gunicorn"
            exe = "gunicorn"
            cmd = [
                python_executable,
                "-m",
                exe,
                "--worker-class=asgi",
                "--access-logfile=-",
                "--error-logfile=-",
                "--bind",
                bind,
                *args,
                entrypoint,
            ]

    else:
        exe = "gunicorn"
        cmd = [
            python_executable,
            "-m",
            exe,
            "--access-logfile=-",
            "--error-logfile=-",
            "--bind",
            bind,
            *args,
            entrypoint,
        ]

    ensure_package(exe, python_executable)
    click.secho(
        f"starting {exe} in {topath(application_dir)}",
        fg="green",
        bold=True,
    )

    click.secho(" ".join(cmd), fg="yellow")
    return subprocess.Popen(cmd, cwd=application_dir, env=os.environ)


def patch_nginx_conf(oldfile: Path, newfile: Path) -> Path:  # noqa: C901, PLR0912
    """Ensure we don't overwrite any existing nginx configuration that has been patched by certbot or other tools."""
    newlines: list[str] = []
    active: bool = False
    with newfile.open("rt", encoding="utf-8") as fp:
        for line in fp:
            if line.lstrip().startswith("# >>> generated by footprint"):
                active = True
            elif line.lstrip().startswith("# <<< generated by footprint"):
                break
            elif active:
                newlines.append(line)
    if not newlines:
        msg = f"no '# >>> generated by footprint' lines found in {newfile.name}!"
        click.secho(msg, fg="red", err=True)
        raise click.Abort
    stem = f"{newfile.stem}-patched{newfile.suffix}"
    if os.access(newfile.parent, os.W_OK):  # noqa: SIM108
        nnewfile = newfile.parent / stem
    else:
        nnewfile = Path(tempfile.gettempdir()) / stem
    certbot = "# managed by Certbot" in oldfile.read_text(encoding="utf-8")
    with nnewfile.open("wt", encoding="utf-8") as fp:
        patched = False
        active = False

        with oldfile.open("rt", encoding="utf-8") as olfp:
            for line in olfp:
                if line.lstrip().startswith("# >>> generated by footprint"):
                    active = True
                    fp.write(line)
                    for newline in newlines:
                        # skip any listen lines if certbot has already added them
                        if certbot and newline.lstrip().startswith("listen"):
                            continue
                        fp.write(newline)
                    patched = True
                elif line.lstrip().startswith("# <<< generated by footprint"):
                    active = False
                    fp.write(line)
                elif not active:
                    fp.write(line)
    if active:
        nnewfile.unlink(missing_ok=True)
        msg = f"no '# <<< generated by footprint' line found in {oldfile.name}!"
        click.secho(msg, fg="red", err=True)
        raise click.Abort
    if not patched:
        nnewfile.unlink(missing_ok=True)
        if certbot:
            msg = "found certbot managed nginx file but no footprint generated lines to patch!"
            click.secho(msg, fg="red", err=True)
            raise click.Abort
        return newfile
    click.secho(
        f"patched {oldfile.name} to {nnewfile.name}",
        fg="yellow",
        bold=True,
        err=True,
    )
    return nnewfile


def nginx_install(nginxconf: str, *, check_only: bool = False, patch_file: bool = True) -> str | None:  # noqa: C901, PLR0915, PLR0912
    import filecmp

    from ..config import get_config

    nginxfile = Path(nginxconf)

    config = get_config()

    conf = nginxfile.name
    # Ubuntu, RHEL8
    for td in config.nginx_dirs:
        targetd = Path(td)
        if targetd.is_dir():
            break
    else:
        msg = "can't find nginx configuration directory."
        click.secho(msg, fg="red", err=True)
        raise click.Abort
    sudo = which("sudo")
    systemctl = which("systemctl")

    def sudocmd(*args: Any, check: bool = True) -> subprocess.CompletedProcess[bytes]:  # noqa: ANN401
        return subprocess.run([sudo] + [str(a) for a in args], check=check)

    def runcmd(*args: Any, check: bool = True) -> subprocess.CompletedProcess[bytes]:  # noqa: ANN401
        return subprocess.run([str(a) for a in args], check=check)

    def systemctlcmd(*args: Any, check: bool = True) -> int:  # noqa: ANN401
        return subprocess.run(
            [sudo, systemctl] + [str(a) for a in args],
            check=check,
        ).returncode

    conffile = targetd / conf

    exists = conffile.is_file()
    issame = exists and filecmp.cmp(conffile, nginxfile)
    if check_only:
        if exists:
            if issame:
                click.secho(
                    f"nginx file {conf} {'unchanged' if issame else 'changed'}",
                    fg="green" if issame else "yellow",
                )
        else:
            click.secho(f"installed nginx file {conf} does not exist", fg="yellow")
        return None

    if not issame:
        bak = None
        if exists and patch_file:
            # file might have been patched by certbot or other tools so we need to patch it
            nnginxfile = patch_nginx_conf(conffile, nginxfile)
            if os.access(nginxfile.parent, os.W_OK):
                bak = nginxfile.parent / f"{conffile.name}.bak"
            else:
                bak = Path(tempfile.gettempdir()) / f"{conffile.name}.bak"
            runcmd("cp", conffile, bak)
            if filecmp.cmp(conffile, nnginxfile):
                click.secho(f"nginx file {conf} unchanged", fg="green")
                if bak is not None:
                    bak.unlink(missing_ok=True)
                if nnginxfile != nginxfile:
                    nnginxfile.unlink(missing_ok=True)
                return conf
            click.secho(f"warning: overwriting old {conf}", fg="yellow")
            sudocmd("cp", nnginxfile, conffile)
            if nnginxfile != nginxfile:
                nnginxfile.unlink(missing_ok=True)
        else:
            sudocmd("cp", nginxfile, conffile)

        if sudocmd("nginx", "-t", check=False).returncode != 0:
            sudocmd("rm", conffile)
            if bak is not None:
                sudocmd("mv", bak, conffile)
            click.secho("nginx configuration faulty", fg="red", err=True)
            return None if bak is None else conf
        if bak is not None:
            bak.unlink(missing_ok=True)

        systemctlcmd("restart", "nginx")
    else:
        click.secho(f"nginx file {conf} unchanged", fg="green")
    return conf


def nginx_uninstall(nginxconf: str, *, save_copy: bool = False) -> None:
    from ..config import get_config

    config = get_config()
    nginxfile = Path(nginxconf)
    conf = nginxfile.name
    if "." not in conf:
        conf += ".conf"
    sudo = which("sudo")
    systemctl = which("systemctl")

    def sudocmd(*args: str, check: bool = True) -> subprocess.CompletedProcess[bytes]:
        return subprocess.run([sudo, *args], check=check)

    def cmd(*args: str, check: bool = True) -> subprocess.CompletedProcess[bytes]:
        return subprocess.run([*args], check=check)

    def systemctlcmd(*args: str, check: bool = True) -> int:
        return subprocess.run([sudo, systemctl, *args], check=check).returncode

    for d in config.nginx_dirs:
        fname = Path(d) / conf
        if fname.is_file():
            if save_copy:
                cp = Path.cwd() / f"{fname.name}.save"
                click.secho(f"saving copy of {fname} to {cp}", fg="yellow", err=True)
                cmd("cp", str(fname), str(cp))
            sudocmd("rm", str(fname))
            systemctlcmd("restart", "nginx.service")
            return

    click.secho(f"no nginx file {nginxfile}", fg="yellow", err=True)


NGINX_ARGS = {
    "access_log": "'on' or 'off'. log static asset requests [default:off]",
    "app": "entrypoint to app",
    "application_dir": "locations of repo",
    "appname": "application name [default: directory name]",
    "authentication": "authentication file name",
    "client_max_body_size": "maximum allowed size of the client request body [default: 10M]",
    "expires": "expires header for static files [default: off] e.g. 30d",
    "extra": "extra (legal) nginx commands for proxy",
    "host": "proxy to a backend [default: use unix socket]",
    "listen": "listen on port [default: 80]",
    "log_format": "specify the log_format",
    "port": "backend TCP/IP port to use",
    "prefix": "url prefix for application [default: /]",
    "root": "static files root directory",
    "root_prefix": "location prefix to use (only used if root is defined)",
    "root_location_match": "regex for matching static directory files",
    "server_name": "name of website",
    "deferred": "deferred connection for listen port (boolean)",
    "uwsgi": "use uwsgi protocol [default: false]",
}

NGINX_HELP = f"""
Generate a nginx conf file for website.

Use footprint config nginx website ... etc.
with the following arguments:

\b
{make_args(NGINX_ARGS)}
\b
example:
\b
footprint config nginx mcms.plantenergy.edu.au access-log=on
\b
"""


def appname_func(params: dict[str, Any]) -> str:
    app = str(params["application_dir"])
    return str(split(app)[-1])


def nginx(  # noqa: C901, PLR0915, PLR0912
    application_dir: Path,
    server_name: str,
    args: list[str] | None = None,
    *,
    template_name: str | None = None,
    help_args: dict[str, str] | None = None,
    check: bool = True,
    output: str | IO[str] | Path | None = None,
    extra_params: dict[str, Any] | None = None,
    checks: list[tuple[str, CHECKTYPE]] | None = None,
    ignore_unknowns: bool = False,
    default_values: list[tuple[str, CONVERTER]] | None = None,
    convert: dict[str, Callable[[Any], Any]] | None = None,
    exclusive: bool = False,
    python_executable: str | None = None,
) -> str:
    """Generate an nginx configuration for application."""
    from jinja2 import UndefinedError

    from ..config import get_config

    if args is None:
        args = []

    if application_dir is None:
        msg = "no application directory"
        raise click.BadParameter(msg)

    if help_args is None:
        help_args = NGINX_ARGS

    application_dir = topath(application_dir)
    template = get_template(template_name or "nginx.conf", application_dir)

    known = get_known(help_args) | {"_staticdirs", "toplevel", "_error_pages", "_exclude_urls", "_routes"}
    # directory to match with / for say /favicon.ico
    root_location_match = None
    params: dict[str, Any] = {}
    try:
        params = {k: v for k, v in footprint_config(application_dir, "nginx").items() if k in known}
        params.update(fix_params(args or [], convert or {}))
        if extra_params:
            params.update(extra_params)

        prefix = params.get("prefix", "")
        if "root" in params:
            root = str(topath(application_dir / str(params["root"])))
            params["root"] = root
            rp = params.get("root_prefix")
            staticdirs = [StaticFolder(rp if rp is not None else prefix, root, rewrite=False)]
        else:
            staticdirs = []
        # if the params have an app value use that as the entrypoint
        entrypoint = params.get("app")
        if entrypoint is None:
            entrypoint = get_app_entrypoint(application_dir)
            if ":" not in entrypoint:
                entrypoint += ":application"
        routes: list[str] = []
        if entrypoint != "@none":
            sd, routes = introspect(
                application_dir, entrypoint, exclusive=exclusive, prefix=prefix, python_executable=python_executable
            )
            staticdirs.extend(sd)
            if exclusive and routes:
                params["_routes"] = routes
                click.secho(
                    f"Warning: exclusive routes: ^/($|{'|'.join(routes)})",
                    err=True,
                    fg="yellow",
                    bold=True,
                )

        error_pages = list(has_error_page(staticdirs, error_pages=[401, 403, 404, 500]))
        params["_error_pages"] = error_pages
        params["_staticdirs"] = staticdirs
        for s in staticdirs:
            if not s.url:  # top level?
                root_location_match = url_match(s.folder)
        # need a root directory for server
        if "root" not in params and not staticdirs:
            params["root"] = topath(application_dir)
        # add any defaults
        defaults: list[tuple[str, CONVERTER]] = [
            ("application_dir", lambda _: application_dir),
            ("appname", appname_func),
            ("root", lambda _: staticdirs[0].folder),
            ("server_name", lambda _: server_name),
            ("uwsgi", lambda _: False),
        ]

        if default_values:
            defaults.extend(default_values)

        for key, default_func in defaults:
            if key not in params:
                v = default_func(params)
                if v is not None:
                    params[key] = v

        def isint(s: str | int) -> bool:
            return isinstance(s, int) or s.isdigit()

        if "host" in params:
            h = params["host"]
            if isint(h):
                params["host"] = "127.0.0.1"
                params["port"] = h
            elif ":" in h:
                s, h = h.rsplit(":", maxsplit=1)
                params["host"] = s
                params["port"] = h

        if "port" not in params:
            params["port"] = 8000

        if root_location_match is not None and "root_location_match" not in params:
            params["root_location_match"] = root_location_match
        if "toplevel" not in params and not root_location_match:
            d = find_toplevel(str(application_dir))
            if d:
                params["toplevel"] = str(topath(application_dir / d))

        if "toplevel" in params:
            params["toplevel"] = str(topath(params["toplevel"]))

        if check:
            msg = check_app_dir(str(application_dir))
            if msg:
                raise click.BadParameter(msg, param_hint="application_dir")

            if not ignore_unknowns:
                extra = set(params) - known
                if extra:
                    msg = f"unknown arguments {extra}"
                    raise click.BadParameter(
                        msg,
                        param_hint="params",
                    )
            failed: list[str] = []
            checks = (checks or []) + [
                to_check_func("root", isdir, '"{root}" is not a directory'),
                to_check_func("toplevel", isdir, '"{toplevel}" is not a directory'),
            ]
            for key, func in checks:
                if key in params:
                    v = params[key]
                    msg = func(key, v)
                    if msg is not None:
                        click.secho(
                            msg,
                            fg="yellow",
                            bold=True,
                            err=True,
                        )
                        failed.append(key)
                if failed:
                    raise click.Abort

        res = template.render(Config=get_config(), **params)
        to_output(res, output)
    except UndefinedError as e:
        undefined_error(e, template, params)
        raise click.Abort from e
    return res


@config.command(name="nginx", help=NGINX_HELP)
@template_option
@config_options
@click.option(
    "--no-static",
    is_flag=True,
    help="Don't try to introspect static files. (Useful for non-flask websites)",
)
@click.option(
    "-x",
    "--404",
    "exclude_urls",
    type=click.Path(exists=True, dir_okay=False, file_okay=True, path_type=Path),
    help="""list of urls to immediately return 404 for (one per line)""",
)
@ignore_unknowns_option
@click.option(
    "--exclusive",
    is_flag=True,
    help="""add a negative assertion to the known urls of the app.
 (Caution you can't add any new routes to the app after this)""",
)
@python_executable_option
# @click.option("--asgi", is_flag=True, help="this is an ASGI application.", deprecated="It is unused now.")
@app_dir_option
@click.argument("server_name")
@click.argument("params", nargs=-1)
def nginx_cmd(
    application_dir: Path | None,
    server_name: str,
    template: str | None,
    *,
    exclude_urls: Path | None,
    params: list[str],
    output: str | None,
    no_check: bool,
    ignore_unknowns: bool = False,
    no_static: bool = False,
    exclusive: bool = False,
    python_executable: str | None = None,
) -> None:
    """Generate nginx config file.

    PARAMS are key=value arguments for the template.
    """
    # see https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-20-04
    # place this in /etc/systemd/system/
    params = list(params)
    if no_static:
        params.append("app=@none")

    urls = []
    if exclude_urls:
        with exclude_urls.open("r", encoding="utf-8") as fp:
            for line in fp:
                line = line.strip()
                if line and line.startswith("/"):
                    urls.append(re.escape(line[1:]))
    nginx(
        application_dir or Path.cwd(),
        server_name,
        params,
        template_name=template,
        check=not no_check,
        output=output,
        extra_params={"_exclude_urls": urls},
        exclusive=exclusive,
        ignore_unknowns=ignore_unknowns,
        python_executable=python_executable,
    )


@config.command(name="nginx-run")
@click.option(
    "-p",
    "--port",
    default=5000,
    help="port for nginx to listen",
    show_default=True,
)
@click.option(
    "-u",
    "--upload-max",
    default="40M",
    help="""maximum file upload size possible.
    (if you try to upload more than this you will get mysterious permission denied errors to `/var/lib/nginx/body`)""",
    show_default=True,
)
@click.option(
    "--entrypoint",
    help="web application entrypoint. If not specified will try to find it in the application directory",
)
@asgi_option
@click.option("--browse", is_flag=True, help="open web application in browser")
@app_dir_option
@webserver_option
@click.option(
    "-x",
    "--no-start",
    "no_start_app",
    is_flag=True,
    help="don't start the website in background",
    show_default=True,
)
@python_executable_option
@click.argument("nginxfile", type=click.File("rt", encoding="utf-8"), required=True)
@click.argument("server_args", nargs=-1)
def nginx_run_cmd(  # noqa: C901, PLR0915
    nginxfile: IO[str],
    application_dir: Path | None,
    entrypoint: str | None,
    *,
    port: int,
    upload_max: str,
    server_args: tuple[str, ...],
    browse: bool,
    asgi: bool,
    python_executable: str | None,
    no_start_app: bool = False,
    server: str | None = None,
) -> None:
    """Run nginx as a non daemon process using the specified nginxfile.

    This will test the generated nginx configuration file (especially the delivery of static files
    and 404 errors).
    """
    import signal
    from tempfile import NamedTemporaryFile

    from ..utils import browser

    nginx_exe = which("nginx")

    webserver = None
    if not no_start_app:
        webserver = server or find_webserver(asgi=asgi, python_executable=python_executable)

    def once(m: str) -> Callable[[re.Match[str]], str]:
        done = False

        def f(_r: re.Match[str]) -> str:
            nonlocal done
            if done:
                return ""
            done = True
            return m

        return f

    def get_server() -> tuple[str, str | None]:
        """Parse nginx.conf file for server and host."""
        access_re = re.compile("access_log [^;]+;")  # remove access log entries
        # see comment in nginx-app.conf about client_body_buffer_size and client_max_body_size
        max_body_re = re.compile("(client_max_body_size|client_body_buffer_size) [^;]+;")
        listen_re = re.compile("listen [^;]+;")  # replace listen {port}; with our port
        proxy_pass_re = re.compile(
            r"(?:proxy_pass|uwsgi_pass)\s+([^\s]+)/?\s*;",
        )  # find where the proxy app.sock is..
        # search for say:
        #    upstream app {
        #        server unix:{{application_dir}}/app.sock fail_timeout=0;
        #    } # noqa: ERA001
        server_re = re.compile(r"server\s+([^{\s]+)/?.*;")

        server = nginxfile.read()
        # remove old access_log and replace listen commands
        server = access_re.sub("", server)
        server = max_body_re.sub("", server)
        server = listen_re.sub(once(f"listen {port};"), server)
        # find unix socket locations
        m = server_re.search(server) or proxy_pass_re.search(server)
        bind = None if not m else m.group(1)
        if bind and bind.startswith("http://"):
            bind = bind[len("http://") :]
        return server, bind

    template: Template = get_template("nginx-app.conf", application_dir)
    server, bind = get_server()
    if not bind:
        click.secho(f"can't find bind entrypoint in file: {nginxfile}", err=True, fg="red")
        raise click.Abort
    # bind is unix:/path/to/app.sock or host:port
    application_dir = application_dir or Path.cwd()
    entrypoint = entrypoint or get_app_entrypoint(application_dir)
    nginx_conf = template.render(server=server, upload_max=upload_max)
    threads: list[threading.Thread] = []
    app = None

    with NamedTemporaryFile("w") as fp:
        fp.write(nginx_conf)
        fp.flush()
        url = f"http://127.0.0.1:{port}"
        click.secho(f"listening on {url}", fg="green", bold=True)
        if not no_start_app:
            assert webserver is not None  # noqa: S101
            app = run_app(
                application_dir,
                bind,
                entrypoint,
                asgi=asgi,
                webserver=webserver,
                args=server_args,
                python_executable=python_executable,
            )
        else:
            click.secho(
                f"expecting app running in {application_dir} bound to {bind}",
                fg="magenta",
                bold=True,
            )
        if browse:
            threads.append(browser(url))
        try:
            subprocess.run([nginx_exe, "-c", fp.name], check=False)
        finally:
            if app is not None:
                if webserver == "gunicorn":
                    os.kill(app.pid, signal.SIGTERM)
                else:
                    os.kill(app.pid, signal.SIGINT)
            for thrd in threads:
                thrd.join(timeout=2.0)


@config.command(name="nginx-install")
@click.option(
    "--check-only",
    is_flag=True,
    help="check if nginx differs from existing config",
)
@click.option(
    "--no-patch",
    is_flag=True,
    help="Just overwrite old nginx config file with new instead of patching it."
    " (useful if you don't want to keep certbot changes).",
)
@click.argument(
    "nginxfile",
    type=click.Path(exists=True, dir_okay=False, file_okay=True),
)
def nginx_install_cmd(nginxfile: str, *, check_only: bool, no_patch: bool) -> None:
    """Install nginx config file."""
    # install frontend
    conf = nginx_install(nginxfile, check_only=check_only, patch_file=not no_patch)
    if not check_only:
        if conf is None:
            raise click.Abort

        click.secho(f"{conf} installed!", fg="green", bold=True)


@config.command(name="nginx-uninstall")
@click.option(
    "-s",
    "--save-copy",
    default=False,
    is_flag=True,
    help="save a copy of the nginx config file before uninstalling",
)
@click.argument("nginxfile")
def nginx_uninstall_cmd(nginxfile: str, *, save_copy: bool) -> None:
    """Uninstall nginx config file."""
    nginx_uninstall(nginxfile, save_copy=save_copy)

    click.secho(f"{nginxfile} uninstalled!", fg="green", bold=True)


@config.command(name="nginx-ssl", hidden=True)
@click.option("--days", default=365, help="days of validity")
@click.argument(
    "server_name",
    required=True,
)
def nginx_ssl_cmd(server_name: str, days: int = 365) -> None:
    """Generate openssl TLS self-signed key for a website."""
    ssl_dir = "/etc/ssl"
    openssl = which("openssl")
    sudo = which("sudo")

    country = server_name.rsplit(".", maxsplit=1)[-1].upper()

    cmd = [
        sudo,
        openssl,
        "req",
        "-x509",
        "-noenc",
        "-days",
        str(days),
        "-newkey",
        "rsa:4096",
        "-keyout",
        f"{ssl_dir}/private/{server_name}.key",
        "-out",
        f"{ssl_dir}/certs/{server_name}.pem",
        "-subj",
        f"/C={country}/CN={server_name}",
    ]

    subprocess.run(cmd, check=True)
    click.secho(f"written keys for {server_name} to {ssl_dir}", fg="green")
