# Run nginx as a normal console program, not as a daemon
daemon off;
pid /tmp/nginx.pid;
# Log errors to stdout
error_log /dev/stdout info;

events {} # Boilerplate

http {
  # Print the access log to stdout
  access_log /dev/stdout;
  {# so we are running nginx as a normal user but we can't write to /var/lib/nginx/body
    which is where file uploads are stored by default.  So we need to increase the buffer
    size to having nginx write to this directory.... cross fingers!
  #}
  client_body_buffer_size {{upload_max|default('40M')}};
  include /etc/nginx/mime.types;
  # embed - a slightly altered version of - `footprint config nginx ...`
  {{server}}
}
